name: Android Build CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib \
          g++-multilib libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev \
          libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig
        
    - name: Build status check
      run: |
        echo "构建环境检查完成"
        echo "Android源码编译需要手动在本地进行"
        echo "请参考README.md中的详细步骤"
